---
title: "Provo Orem Scenario Maker"
author: "Nate Lant"
date: "8/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
# devtools::install_github("dkahle/ggmap")
# library(ggmap)
library(leaflet)
library(Hmisc)
```

```{r}
# read in the data
trips <- read_csv("data/final_trips.csv")
persons <- read_csv("data/final_persons.csv")
facilities <- read_csv("data/facility_ids.csv")
households <- read_csv("data/hhcoord.csv")

# filter hh by coordinates of provo orem boundary
hh <- households %>%
  filter(latitude < 40.30416667 & longitude > -111.72138889,
         latitude > 40.21194444 & longitude < -111.61972222)



```

This file will filter the trips and persons files to only the origins and destinations
of individuals and households in the Provo/Orem area. The modifided trips and persons
files will be used in the WAV microtransit scenario.

```{r}
#First filter origins AND desitnations to TAZs in provo orem
trips_provo_orem <- trips %>%
  filter(origin %in% hh$TAZ &
         destination %in% hh$TAZ)

# Next filter persons to persons making ANY trips inside provo orem
persons_provo_orem <- persons %>%
  filter(person_id %in% trips_provo_orem$person_id)

# If any trips are have origin or destination outside of provo orem, cut that person
# we are left with list of trips of people that made all trips inside provo orem
provo_trips <- trips %>% 
  filter(person_id %in% persons_provo_orem$person_id) %>% # this step makes it waaaaay faster
  group_by(person_id) %>%
  #if person has a trip not in the zone range, cut them out
  filter(!any(origin %nin% hh$TAZ | destination %nin% hh$TAZ))
    
# make persons list of of those making ALL trips inside provo orem
provo_persons <- persons %>%
  filter(person_id %in% provo_trips$person_id)
  
```

```{r}
# collect 100 persons
sample_persons <- provo_persons %>%
  sample_n(100) 

# get the households from the 100 persons (maybe < 100)
# we need the coordinates from the households
sample_hh <- households %>% 
  filter(household_id %in% sample_persons$household_id)

# attach a lat long to the persons file
sample_persons %>%
  left_join(sample_hh, by = c("household_id", "TAZ")) %>%
  write_csv("scenarios/provo_orem/persons100.csv")

#from all trips in provo orem, take only those from 100 sample persons
provo_trips %>%
  filter(person_id %in% sample_persons$person_id) %>%
  write_csv("scenarios/provo_orem/trips100.csv")

```

```{r}
# create households file from sample 100 persons
households %>% 
  filter(household_id %in% sample_persons$household_id) %>%
  write_csv("scenarios/provo_orem/households100.csv")
```






# Households
I want to visualize the households on the map.

```{r}

```

